inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - 'db/migrate/*.rb'
    - 'db/schema.rb'
    - 'bin/setup'
    - 'bin/update'

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'Gemfile'
    - 'Rakefile'

Metrics/BlockLength:
  Exclude:
    - 'config/**/*'
    - 'spec/**/*'
    
Metrics/LineLength:
  Exclude:
    - 'config/**/*'
    - 'spec/**/*'
    - 'Gemfile'
    - 'Rakefile'
