inherit_from: .rubocop_todo.yml

require:
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  NewCops: enable

  TargetRubyVersion: 3.3
  Exclude:
    - 'db/migrate/*.rb'
    - 'lib/templates/**/*'
    - 'vendor/**/*'
    - bin/setup
    - bin/update

Style/Documentation:
  Exclude:
    - 'Gemfile'
    - 'Rakefile'

Metrics/BlockLength:
  Exclude:
    - 'config/**/*'
    - 'db/schema.rb'

Layout/LineLength:
  Exclude:
    - 'config/**/*'
    - 'Gemfile'
    - 'Rakefile'

Style/SignalException:
  Exclude:
    - 'Dangerfile'

# We don't want this
Rails/ApplicationRecord:
  Exclude:
    - 'app/models/paper_trail/version.rb'