services:
  rz:
    build:
      context: .
      args:
        PUID: ${PUID}
        PGID: ${PGID}
      dockerfile: docker/unit/Dockerfile
    environment:
      TEST_HOST: rz
      CHROME_HOSTNAME: chrome # Point to the chrome container for testing
    container_name: rz
    volumes:
      - ./docker/unit/postgresql.conf:/srv/postgres/postgresql.conf:ro
      - ./docker/unit/pg_hba.conf:/srv/postgres/pg_hba.conf:ro
      - db_data:/srv/postgresql
      - ./app:/srv/app
      - ./config:/srv/config
      - ./db:/srv/db
      - ./lib:/srv/lib
      - ./spec:/srv/spec
      - ./Gemfile:/srv/Gemfile
    ports:
      - "3000:3000"
      - "5432"

  # ****************
  # Tools
  # ****************
  # All the containers described below here are not for production use
  # but to assist development

  # PGAdmin
  # Use this to inspect your database and test queries
  pgadmin:
    image: dpage/pgadmin4:4
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    entrypoint: /entrypoint.sh
    volumes:
      - type: bind
        source: ./docker/unit/pgadmin_servers.json
        target: /pgadmin4/servers.json
        read_only: true
    depends_on:
      - rz

  # Selenium Chrome instance
  # This is used to perform browser testing and also to ensure that
  # secure parts of the webapp are not inadvertantly open to the public
  # See the browser specs in /spec/browser.
  # If you have a VNC client, simply login to port 5900 with the
  # password: secret
  chrome:
    image: selenium/standalone-chrome-debug
    container_name: chrome
    environment:
      SCREEN_WIDTH: 1280
      SCREEN_HEIGHT: 1024
    ports:
      - "5900:5900"
    healthcheck:
      test: ["CMD", "curl", "-v", "http://localhost:4444/wd/hub/status"] 
      interval: 10s
      timeout: 5s
      retries: 3
  video:
    platform: linux/amd64
    image: davidsiaw/vrec
    container_name: chromevideo
    environment:
      HOST: 'chrome:5900'
      MP4LOC: '/var/output/out.mp4'
      GIVEUID: "1000"
      GIVEGID: "1000"
    ports:
      - "9494:9494"
    volumes:
      - type: bind
        source: ./vidoutput
        target: /var/output
    depends_on:
      - chrome
volumes:
  db_data:
