services:
  # Unit server
  rails-unit:
    build:
      context: ..
      dockerfile: ./docker/unit/Dockerfile
    container_name: rails-unit
    environment:
      TEST_HOST: rails-unit
      CHROME_HOSTNAME: chrome # Point to the chrome container for testing

  # Selenium Chrome instance
  # This is used to perform browser testing and also to ensure that
  # secure parts of the webapp are not inadvertantly open to the public
  # See the browser specs in /spec/browser.
  # If you have a VNC client, simply login to port 5900 with the
  # password: secret
  chrome:
    image: selenium/standalone-chrome
    container_name: chrome
    environment:
      SCREEN_WIDTH: 1280
      SCREEN_HEIGHT: 1024
    healthcheck:
      test: ["CMD", "curl", "-v", "http://localhost:4444/wd/hub/status"] 
      interval: 10s
      timeout: 5s
      retries: 3
  chromevideo:
    platform: linux/amd64
    image: davidsiaw/vrec
    container_name: chromevideo
    environment:
      HOST: 'chrome:5900'
      MP4LOC: '/var/output/out.mp4'
      GIVEUID: "1000"
      GIVEGID: "1000"
    depends_on:
      - chrome
volumes:
  db_data:
  active_storage:
