version: '3.7'
services:
  # Rails database
  # If you wish to clear the database contents simply run
  # docker-compose down -v
  db:
    image: postgres:alpine
    container_name: db
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres

  # Redis server
  # This server is used as a cache for all temporary data
  # You can of course, make redis have permanent storage, but I
  # recommend using postgres for that.
  redis:
    image: 'redis:alpine'

  # Sidekiq server
  # This is the thing that will perform all delayed jobs, sending
  # emails, do periodic checks etc. I recommend using this to your
  # advantage to automate schedulable tasks.
  sidekiq:
    build: ..
    command: bundle exec sidekiq -C config/sidekiq.yml
    environment:
      DATABASE_URL: postgres://postgres:postgres@db
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - db
      - redis
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s

  # Rails server
  # This is the main server.
  # You can use rails c too by simply going
  # docker-compose exec rails rails c
  # Using this mechanism you can also perform database migrations and rollbacks
  # docker-compose exec rails rails db:migrate
  rails:
    build: ..
    container_name: rails
    command: sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres:postgres@db
      REDIS_URL: redis://redis:6379/0
      CHROME_HOSTNAME: chrome # Point to the chrome container for testing
    depends_on:
      - db
      - redis

  # Selenium Chrome instance
  # This is used to perform browser testing and also to ensure that
  # secure parts of the webapp are not inadvertantly open to the public
  # See the browser specs in /spec/browser.
  # If you have a VNC client, simply login to port 5900 with the
  # password: secret
  chrome:
    image: selenium/standalone-chrome-debug
    container_name: chrome
    ports:
      - "5900:5900"
volumes:
  db_data:
  active_storage:
