postgres: postgres -D /srv/postgres
redis: redis-server
rails: sh waitpg.sh; sh bin/dbsetup; sh waitredis.sh; bundle exec rails s -b 0.0.0.0 -p 3000
sidekiq: sh waitpg.sh && sh waitredis.sh && sleep 5 && bundle exec sidekiq -C config/sidekiq.yml