name: test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: compose up
        run: |-
          PUID="$(id -u)" PGID="$(id -g)" docker compose up -d --wait --build
      - name: show logs
        if: failure()
        run: |-
          docker compose logs rails
      - name: start recording
        run: |-
          docker compose exec rails curl chromevideo:9494/start
      - name: run tests
        run: |-
          docker compose exec rails rspec
      - name: stop recording
        run: |-
          docker compose exec rails curl chromevideo:9494/stop
          sleep 3
      - uses: actions/upload-artifact@v4
        with:
          name: test-video
          path: vidoutput/out.mp4
          if-no-files-found: error
