name: test-unit
on: [push]
jobs:
  test-unit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build and run tests
        run: |
          docker-compose -f .circleci/compose-unit.yml up -d
          timeout 60 bash -c -- 'while [[ "$(docker-compose -f .circleci/compose-unit.yml exec -T rails-unit curl -s -o /dev/null -w ''%{http_code}'' http://localhost:3000/api/v1/health)" != "200" ]]; do sleep 1; printf "."; done'
          docker-compose -f .circleci/compose-unit.yml exec -T rails-unit bundle exec rspec --format progress

